### ISSUE TITLE
Error for skyclient DG

### ISSUE THREAD

**Issue by EpsilonPhoenix** [Dungeons-Guide/Skyblock-Dungeons-Guide#404]
![image](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/assets/129551402/b84c5b17-24f0-474c-a8d4-367dfdcd1460)

The full error:

 java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:170)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
    at sun.security.ssl.InputRecord.read(InputRecord.java:503)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
    at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessController.doPrivileged(AccessController.java:713)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.getResponse(DgAuthUtil.java:70)
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.requestAuth(DgAuthUtil.java:115)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager.reAuth(AuthManager.java:127)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager.lambda$init$0(AuthManager.java:102)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager$$Lambda$208/1952605049.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Vaultrex** [comment]
same issue ^^

**Comment by Xtendera** [comment]
bump. Any solutions? The msg is super annoying

**Comment by tylercharvat3** [comment]
bump

**Comment by cyoung06** [comment]
Should be fixed by now
