### ISSUE TITLE
Auth Error caused by: org.json.JSONException (alt auth error)

### ISSUE THREAD

**Issue by Adolg2137** [Dungeons-Guide/Skyblock-Dungeons-Guide#408]
![Base Profile Screenshot 2023 09 05 - 13 48 24 28](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/assets/144125401/ae5afc89-da3e-4f10-9e09-ea14834e03f0)
Log:
kr.syeyoung.dungeonsguide.launcher.exceptions.http.ResponseParsingException: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
 Problematic Message: upstream connect error or disconnect/reset before headers. reset reason: connection failure
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.getResponse(DgAuthUtil.java:94)
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.requestAuth(DgAuthUtil.java:115)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager.reAuth(AuthManager.java:127)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager.lambda$init$0(AuthManager.java:102)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
    at org.json.JSONTokener.syntaxError(JSONTokener.java:501)
    at org.json.JSONObject.<init>(JSONObject.java:208)
    at org.json.JSONObject.<init>(JSONObject.java:404)
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.getResponse(DgAuthUtil.java:77)
    ... 10 more

**Comment by iyahayki** [comment]
is there a fix its happening to me too

**Comment by GergoEB** [comment]
Something with their API, the endpoint v2.dungeons.guide/api/auth/v2/requestAuth doesnt seem to respond correctly

**Comment by caaom** [comment]
do you have any idea on how i could hide the error

**Comment by GergoEB** [comment]
You can't right now but I might make a thing so you can disable in settings so it only shows once for like 30 seconds (I thought it's temporary but it's starting to annoy me too) I'll send a message here to the repo when I do it

**Comment by cyoung06** [comment]
dupe
