### ISSUE TITLE
Dungeons guide isnt working

### ISSUE THREAD

**Issue by Filakcz** [Dungeons-Guide/Skyblock-Dungeons-Guide#46]
Yesterday it worked fine and today this keeps happening. I didnt change anything. I tried restarting computer twice and opened many times minecraft. Still doesnt work.
**My mods:**
- Optifine
- Skyblock addons
- Dankers skyblock mod
- Bazaarnotifier
- Dungeon rooms
- NotEnoughUpdates
- Dungeons guide
- Skytils
![image](https://user-images.githubusercontent.com/73638102/159129075-f32cc023-c333-4a3b-a7d8-794fbeb8afc0.png)

**Comment by cyoung06** [comment]
Try launching minecraft again

**Comment by SebyHas** [comment]
i have ~same problem
![DGnotrun](https://user-images.githubusercontent.com/14328372/171885537-ffb34728-fc03-4d51-801b-75d607fd0ef2.png)
:

**Comment by meisme11217** [comment]
i have the same issue how did you fix it?

**Comment by simonsaysabit** [comment]
same here java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:170)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
    at sun.security.ssl.InputRecord.read(InputRecord.java:503)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
    at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessController.doPrivileged(AccessController.java:713)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.getResponse(DgAuthUtil.java:70)
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.requestAuth(DgAuthUtil.java:115)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager.reAuth(AuthManager.java:127)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager.lambda$init$0(AuthManager.java:102)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager$$Lambda$307/2099066510.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
