### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by drmrti** [Dungeons-Guide/Skyblock-Dungeons-Guide#484]
**Describe the bug**
when open mineraft i have a popup that i cant get rid of that sais "auth ewrror"

**To Reproduce**
1. open minecraft
2. Click on the "Auth Error" popup
3. See error

**Expected behavior**
I expected minecraft to open normally with nothing to be amiss but htis annoying popup covers a lot of my screen

**Screenshots**

**Desktop (please complete the following information):**
 - Windows
 - Browser Brave
 - Version idk

**Additional context**
It isnt the first time i get this error although the last time i did was a few months ago and id like to either be able to close the popup or for it not to appear this is the log:

kr.syeyoung.dungeonsguide.launcher.exceptions.http.ResponseParsingException: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
 Problematic Message: error code: 521
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.getResponse(DgAuthUtil.java:94)
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.requestAuth(DgAuthUtil.java:115)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager.reAuth(AuthManager.java:127)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager.lambda$init$0(AuthManager.java:102)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager$$Lambda$242/1645262701.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
    at org.json.JSONTokener.syntaxError(JSONTokener.java:501)
    at org.json.JSONObject.<init>(JSONObject.java:208)
    at org.json.JSONObject.<init>(JSONObject.java:404)
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.getResponse(DgAuthUtil.java:77)
    ... 11 more

**Comment by b1n4ryj4n** [comment]
lul u where 1 minute faster than me, i close mine ^^

#485

**Comment by lucasloric** [comment]
same error

**Comment by Kurumi78** [comment]
Made less annoying via #486

**Comment by Mickey786110** [comment]
Is there a fix to this yet btw?

**Comment by Buttercomb** [comment]
same issue here
