### ISSUE TITLE
ResponseParsingException

### ISSUE THREAD

**Issue by b1n4ryj4n** [Dungeons-Guide/Skyblock-Dungeons-Guide#485]
**Describe the bug**
If i start minecraft this error occurs and this stupid error box stay all the time...

kr.syeyoung.dungeonsguide.launcher.exceptions.http.ResponseParsingException: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
 Problematic Message: error code: 521
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.getResponse(DgAuthUtil.java:94)
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.requestAuth(DgAuthUtil.java:115)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager.reAuth(AuthManager.java:127)
    at kr.syeyoung.dungeonsguide.launcher.auth.AuthManager.lambda$init$0(AuthManager.java:102)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
    at org.json.JSONTokener.syntaxError(JSONTokener.java:501)
    at org.json.JSONObject.<init>(JSONObject.java:208)
    at org.json.JSONObject.<init>(JSONObject.java:404)
    at kr.syeyoung.dungeonsguide.launcher.auth.DgAuthUtil.getResponse(DgAuthUtil.java:77)
    ... 10 more

**Comment by b1n4ryj4n** [comment]
duplicate #484
