### ISSUE TITLE
Error on Floor 5 with Secrets

### ISSUE THREAD

**Issue by funkemunky** [Dungeons-Guide/Skyblock-Dungeons-Guide#52]
I'm on floor 5. I do not know the exact mechanism of how this occurs but I'm fairly certain this may be due to a concurrency issue.

```
[10:56:59] [Client thread/INFO]: [CHAT] §r§cThere are blocks in the way!§r
[10:56:59] [pool-27-thread-3/INFO]: [kr.syeyoung.dungeonsguide.pathfinding.ThetaStar:pathfind:101]: Route len: 6
[10:57:00] [Client thread/INFO]: [CHAT] §r§cThere are blocks in the way!§r
[10:57:00] [pool-27-thread-2/INFO]: [kr.syeyoung.dungeonsguide.pathfinding.ThetaStar:pathfind:101]: Route len: 7
[10:57:00] [pool-27-thread-1/INFO]: [kr.syeyoung.dungeonsguide.pathfinding.ThetaStar:pathfind:101]: Route len: 5
[10:57:01] [pool-27-thread-4/INFO]: [kr.syeyoung.dungeonsguide.pathfinding.ThetaStar:pathfind:101]: Route len: 5
[10:57:01] [Client thread/INFO]: [CHAT] §r§cYour Mining Speed Boost has expired!§r
[10:57:01] [pool-27-thread-3/INFO]: [kr.syeyoung.dungeonsguide.pathfinding.ThetaStar:pathfind:101]: Route len: 5
[10:57:02] [Client thread/INFO]: [CHAT] §r§cThis chest has already been searched!§r
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.dungeon.mechanics.DungeonSecret.getSecretStatus(DungeonSecret.java:91)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.dungeon.mechanics.DungeonSecret.getCurrentState(DungeonSecret.java:222)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.dungeon.actions.tree.ActionRoute.onTick(ActionRoute.java:103)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.roomprocessor.GeneralRoomProcessor.lambda$tick$0(GeneralRoomProcessor.java:112)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.roomprocessor.GeneralRoomProcessor$$Lambda$382/1099111189.accept(Unknown Source)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.roomprocessor.GeneralRoomProcessor.tick(GeneralRoomProcessor.java:111)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.eventlistener.DungeonListener.onTick(DungeonListener.java:196)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_DungeonListener_onTick_ClientTickEvent.invoke(.dynamic)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1624)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:121)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:67)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:111)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:34)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.lang.Class.newInstance(Class.java:442)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.dungeon.mechanics.DungeonSecret.getSecretStatus(DungeonSecret.java:91)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.dungeon.mechanics.DungeonSecret.getCurrentState(DungeonSecret.java:222)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.dungeon.actions.tree.ActionRoute.onTick(ActionRoute.java:103)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.roomprocessor.GeneralRoomProcessor.lambda$tick$0(GeneralRoomProcessor.java:112)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.roomprocessor.GeneralRoomProcessor$$Lambda$382/1099111189.accept(Unknown Source)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.roomprocessor.GeneralRoomProcessor.tick(GeneralRoomProcessor.java:111)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at kr.syeyoung.dungeonsguide.eventlistener.DungeonListener.onTick(DungeonListener.java:196)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_DungeonListener_onTick_ClientTickEvent.invoke(.dynamic)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1624)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:121)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:67)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:111)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:34)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at java.lang.Class.newInstance(Class.java:442)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[10:57:02] [Client thread/INFO]: [kr.syeyoung.dungeonsguide.eventlistener.DungeonListener:onTick:202]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
This is on Forge 1.8.9
Mods;
DungeonsGuide v3.7.7
Skytils 1.2.5
ToggleSneak 1.8.9 v3.2.2
PlayerAPI1.8.9-1.0
Patcher 1.8.1
NoEnoughUpdates-2.0.0
Orange's Animation 6.7
KeyStrokes 8.1

I have FastRender off and left DungeonsGuide secret finder settings at default; using the Theta pathfinding algorithim. If you need more info let me know.

**Comment by cyoung06** [comment]
Issue has been fixed
