### ISSUE TITLE
Cannot start Minecraft.

### ISSUE THREAD

**Issue by olavorw** [Dungeons-Guide/Skyblock-Dungeons-Guide#533]
# ISSUE FIXED - USE A NEW DIRECTORY

**Description**
Crashes when starting miencraft.

**Crash Report**
Error: java.lang.NullPointerException: Initializing game
Error Code: -1
Crash Log Report:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  DGTweaker (dungeonsguide-4.0.0-beta10.0-standalone.jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  AsmHelperLoadingPlugin (ctjs-2.2.1-1.8.9.jar)
  ModTweaker (Patcher-1.8.9 (1.8.9).jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.7.3+7380-for-MC-1.8.9.jar)
  PatcherTweaker (Patcher-1.8.9 (1.8.9).jar)
  Skytils On Top (Skytils-1.9.8.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 7/29/24 10:48 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraftforge.fml.client.FMLClientHandler.logMissingTextureErrors(FMLClientHandler.java:954)
	at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:410)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:512)
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:220)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:116)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fml.client.FMLClientHandler.logMissingTextureErrors(FMLClientHandler.java:954)
	at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:410)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:220)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:116)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Game Directory: \AppData\Roaming\.minecraft
	ChatTriggers modules: [Module{name=BeaconBeam,version=1.0.1}, Module{name=guimanager,version=0.1.7}, Module{name=PromiseV2,version=1.0.4}, Module{name=soopyAddonsData,version=0.0.1}, Module{name=soopyApis,version=0.1.17}, Module{name=SoopyV2,version=2.1.202}]
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 464660832 bytes (443 MB) / 1375731712 bytes (1312 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version        | Source                                      |
	| ------ | --------------------- | -------------- | ------------------------------------------- |
	| UCHIJA | mcp                   | 9.19           | minecraft.jar                               |
	| UCHIJA | FML                   | 8.0.99.99      | forge-1.8.9-11.15.1.2318-1.8.9.jar          |
	| UCHIJA | Forge                 | 11.15.1.2318   | forge-1.8.9-11.15.1.2318-1.8.9.jar          |
	| UCHIJA | dungeons_guide        | unknown        | minecraft.jar                               |
	| UCHIJA | essential             | 1.0.0          | Essential (forge_1.8.9).processed.jar       |
	| UCHIJA | oneconfig             | 0.2.2-alpha212 | OneConfig (1.8.9-forge).jar                 |
	| UCHIJA | chattriggers          | 2.2.1          | ctjs-2.2.1-1.8.9.jar                        |
	| UCHIJA | dungeonrooms          | 3.4.1          | Dungeon_Rooms-3.4.1.jar                     |
	| UCHIJA | dungeons_guide_loader | 4.0.0          | dungeonsguide-4.0.0-beta10.0-standalone.jar |
	| UCHIJA | Danker's Skyblock Mod | 2.2            | MC.1.8.9.Danker.s.Skyblock.Mod.-.2.2.jar    |
	| UCHIJA | notenoughupdates      | 2.3.0          | NotEnoughUpdates-2.3.0.jar                  |
	| UCHIJA | patcher               | 1.8.9          | Patcher-1.8.9 (1.8.9).jar                   |
	| UCHIJA | text_overflow_scroll  | 1.4.0          | Scrollable Tooltips-1.4 (1.8.9).jar         |
	| UCHIJA | skyblockaddons        | 1.7.3          | SkyblockAddons-1.7.3+7380-for-MC-1.8.9.jar  |
	| UCHIJA | skytils               | 1.9.8          | Skytils-1.9.8.jar                           |
	| UCHIJA | soopyv2forge          | 1.1            | soopyv2forge-1.1.jar                        |

	Loaded coremods (and transformers): 
DGTweaker (dungeonsguide-4.0.0-beta10.0-standalone.jar)
  kr.syeyoung.dungeonsguide.launcher.coremod.EventBusTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  club.sk1er.mods.scrollabletooltips.forge.ClassTransformer
AsmHelperLoadingPlugin (ctjs-2.2.1-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
ModTweaker (Patcher-1.8.9 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.7.3+7380-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
PatcherTweaker (Patcher-1.8.9 (1.8.9).jar)
  club.sk1er.patcher.tweaker.ClassTransformer
Skytils On Top (Skytils-1.9.8.jar)
  gg.skytils.skytilsmod.asm.SkytilsTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 555.99' Renderer: 'NVIDIA GeForce RTX 3080/PCIe/SSE2'
	Skytils Debug Info: {HasBetterFPS=false, BetterFPS Version=NONE, Disabled Start Checks=false}
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 4.6.0 NVIDIA 555.99, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: §aFurfSky Reborn §8§lFULL§8.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 7700X 8-Core Processor 
```

**To Reproduce**
1. Put the mods in your mod folder and start minecraft.

**Expected behavior**
Just works

**Screenshots**
![image](https://github.com/user-attachments/assets/7427cc80-51aa-4fb8-96ea-476b496f9930)

**Additional mods used** (All latest versions)
- ChatTriggers
- Dungeon Rooms
- Danker
- NEU
- Patcher
- Scrollable Tooltips
- SBA
- SBE
- SoopyV2
- Skytils

**Attempted Fixes**
- Deleted config folder
- Deleted bin folder
- Deleted assets folder
- Used a brand new directory

**Comment by olavorw** [comment]
```diff
**Attempted Fixes**
+ Deleted bin folder
+ Deleted assets folder
```
Still doesn't work.

**Comment by cyoung06** [comment]
btw dupe of #513
