### ISSUE TITLE
Dungeons Guide wont load with version 12.2 and 12.3

### ISSUE THREAD

**Issue by b1n4ryj4n** [Dungeons-Guide/Skyblock-Dungeons-Guide#561]
```
kr.syeyoung.dungeonsguide.launcher.exceptions.DungeonsGuideUnloadingException: jar:unknown
    at kr.syeyoung.dungeonsguide.launcher.loader.JarLoader.unloadDungeonsGuide(JarLoader.java:125)
    at kr.syeyoung.dungeonsguide.launcher.Main.unload(Main.java:184)
    at kr.syeyoung.dungeonsguide.launcher.Main.tryReloading(Main.java:153)
    at kr.syeyoung.dungeonsguide.launcher.Main.initEvent(Main.java:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
    at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:220)
    at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:116)
    at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
    at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
    at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
    Suppressed: kr.syeyoung.dungeonsguide.launcher.exceptions.DungeonsGuideLoadingException: Exception occurred while calling init
Info: jar:unknown
        at kr.syeyoung.dungeonsguide.launcher.Main.load(Main.java:203)
        at kr.syeyoung.dungeonsguide.launcher.Main.reload(Main.java:256)
        at kr.syeyoung.dungeonsguide.launcher.Main.tryReloading(Main.java:149)
        ... 72 more
    Caused by: java.lang.NoSuchMethodError: org.json.JSONArray.toList()Ljava/util/List;
        at kr.syeyoung.dungeonsguide.mod.party.PartyManager.createMatcher(PartyManager.java:93)
        at kr.syeyoung.dungeonsguide.mod.party.PartyManager.<init>(PartyManager.java:112)
        at kr.syeyoung.dungeonsguide.mod.party.PartyManager.<clinit>(PartyManager.java:52)
        at kr.syeyoung.dungeonsguide.mod.features.impl.party.FeaturePartyReady.isHUDViewable(FeaturePartyReady.java:54)
        at kr.syeyoung.dungeonsguide.mod.features.richtext.TextHUDFeature.isVisible(TextHUDFeature.java:59)
        at kr.syeyoung.dungeonsguide.mod.features.AbstractGuiFeature.checkVisibility(AbstractGuiFeature.java:46)
        at kr.syeyoung.dungeonsguide.mod.features.AbstractGuiFeature.setEnabled(AbstractGuiFeature.java:35)
        at kr.syeyoung.dungeonsguide.mod.features.impl.party.FeaturePartyReady.<init>(FeaturePartyReady.java:49)
        at kr.syeyoung.dungeonsguide.mod.features.FeatureRegistry.<clinit>(FeatureRegistry.java:242)
        at kr.syeyoung.dungeonsguide.mod.DungeonsGuide.init(DungeonsGuide.java:226)
        at kr.syeyoung.dungeonsguide.launcher.Main.load(Main.java:201)
        ... 74 more
Caused by: kr.syeyoung.dungeonsguide.launcher.exceptions.ReferenceLeakedException: Reference Leaked
    ... 75 more
```
openjdk: 
- jdk8u422

other mods i use:
- NotEnoughUpdates-2.4.0.jar
- Optibye-1.0.0-dep.jar
- Patcher-1.8.9 (1.8.9).jar
- PolySprint-1.8.9-forge-1.0.0.jar
- preview_OptiFine_1.8.9_HD_U_M6_pre2.jar
- Scatha-Pro_v1.2.3.1.jar
- SkyblockAddons-1.9.0-beta.18.1+384-for-MC-1.8.9.jar
- SkyblockExtras-2.2.0-pre24-RELEASE.jar
- SkyHanni-0.28.Beta.1.jar
- WaterSolver.jar

**Comment by b1n4ryj4n** [comment]
with 12.4 it works :) 

ty for the fix 👍

**Comment by cyoung06** [comment]
my honest reaction to this issue is that why didn't it link to discord :/

**Comment by cyoung06** [comment]
Ohhh because it went over 2000 char limit
